# Generated by Django 4.1.4 on 2023-01-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Korzinka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=20)),
                ('narxi', models.IntegerField()),
                ('rasm', models.CharField(max_length=200)),
                ('son', models.DecimalField(decimal_places=2, default=1, max_digits=100)),
                ('tg_id', models.IntegerField()),
                ('ism', models.CharField(max_length=50)),
            ],
        ),
    ]
